### ISSUE TITLE
Twitter API 1.1 broke avatar permalinks

### ISSUE THREAD

**Issue by hugovk** [aparrish/twitteravatarkeyboard#1]
Unfortunately the users/profile_image permalinks from API v1.0 have been removed and aren't in API 1.1 so there's lot's of broken images:

https://api.twitter.com/1/users/profile_image?screen_name=a&size=normal

**Comment by aparrish** [comment]
yup! this is broken and I don't know how to fix it. it was only ever a weird hack anyway.
